---
repo_path: ~/wtc
navigator_url: https://navigator.wethinkcode.co.za
username: lmolapo021@student.wethinkcode.co.za
review_manager_url: https://review-manager.wethinkcode.co.za
keycloak_url: https://keycloak.wethinkcode.co.za
...
